services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_DB_URI: "mongodb://root:password@mongodb:27017/chat?authSource=admin"
      JWT_SECRET: "your_jwt_secret"
      NODE_ENV: "development"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password