# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  namespace: chat-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: milinddethe15/chat-cluster-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_DB_URI
          value: mongodb://root:password@mongodb.chat-cluster.svc.cluster.local:27017/chat?authSource=admin
        - name: JWT_SECRET
          value: strongest
        - name: NODE_ENV
          value: development
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  namespace: chat-cluster
spec:
  selector:
    app: chat-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP