# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: chat-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
      - name: chat-frontend
        image: vickybesra2000/chat_cluster_frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
  namespace: chat-cluster
spec:
  type: LoadBalancer  
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP   
  selector:
    app: chat-frontend
  
